### ISSUE TITLE
[macOS 11.5.2] It shows the wrong position

### ISSUE THREAD

**Issue by lijy91** [lesnitsky/native_context_menu#5]
![IMG_20210928_092754](https://user-images.githubusercontent.com/3889523/135007613-bf7e976a-ecfd-40ca-b3b6-a32446ca7a1f.jpeg)

**Comment by lesnitsky** [comment]
I was seeing exactly the same before 24d9b969b70bf5938d21a70eedf06dbd3b254d9b

**Comment by lijy91** [comment]
On my mac, the `contentView` coordinates are flipped.

![image](https://user-images.githubusercontent.com/3889523/135061908-a7380e61-b890-4d13-bd61-84e8b01397b5.png)
